FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --production

COPY . .

RUN npm install -g pm2

ENV NODE_ENV=production
ENV PORT=3001

EXPOSE 3001

CMD ["pm2-runtime", "file-name-bro"]
